Attract Helpers
KalleHallden/BookOmatic pull request #26
Opened 2020-03-20 15:20 UTC by SadFarm1

Hey Kalle!

Just wanted to give you some tips on open source projects. Here is an excellent example of an open-source project https://github.com/crybapp . Some ways you can get people helping out with your document is to add a tag named "good first issue". That would bring new people in to help out and more experienced people in to help out with the harder issues.

I updated the readme to include a "want to help out" section and removed a bullet point from the description.

2020-03-20 19:42 UTC, TNeri1 commented
I like your addition to attract new comers. I am still in school, but I have learned C++ (Just finished up OOP, now getting on to Data Structures), SQL, R, JavaScript, HTML, CSS, and now learning Python. I hope I can be able to contribute in some small way or another. I want to help!

2020-03-21 00:34 UTC, SadFarm1 commented
@TNeri1 That's exactly my goal! I want to administer to as many newcomers as possible to help the project ans well as the individual to learn more about the topic.

2020-03-21 18:27 UTC, robsmithw requested changes

2020-03-21 18:27 UTC, robsmithw commented on README.md
> +I encourage everyone to help out with this project, no matter what your skill base is. If you know any form of coding, look at the issues (in special those labelled as "good first issue", for the new
I like what you're going for but the last part seems a bit wordy.

2020-03-21 23:41 UTC, SadFarm1 commented
This seems like a lost cause, thanks guys

2020-03-21 23:41 UTC, closed without merging